install.packages("arules")
install.packages("plyr")
install.packages("dplyr")
install.packages("readxl")
library(arules)
library(plyr)
library(dplyr)
library(readxl)
getwd()
setwd("C:\\Users\\ASUS\\Desktop\\R_Practise")
reatil=read_excel("Online Retail.xlsx")
View(reatil)
reatil$InvoiceDate=as.Date(reatil$InvoiceDate)
tran_data=ddply(reatil,c("InvoiceNo","InvoiceNo"),
                function(df)paste(df$Description,collapse = ","))
names(reatil)
View(head(tran_data))
tran_data$InvoiceNo<-NULL
colnames(tran_data)=c("Items")
write.csv(tran_data,"Basket.csv",row.names = F)
?write.csv()
transactions=read.transactions("Basket.csv",format = 'basket',sep = ',')
summary(transactions)
rules<-apriori(transactions,parameter=list(support=0.001,conf=1))
summary(rules)
inspect(rules)
data("AirPassengers")
View(AirPassengers)
plot(AirPassengers)
